"""add observations table

Revision ID: 5cda57afee5d
Revises: b734f3f99abc
Create Date: 2026-07-06 17:05:55.091065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cda57afee5d'
down_revision: Union[str, Sequence[str], None] = 'b734f3f99abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('code_system', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('reference_range', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_observations_source_external_id')
    )
    op.create_index(op.f('ix_observations_category'), 'observations', ['category'], unique=False)
    op.create_index(op.f('ix_observations_code'), 'observations', ['code'], unique=False)
    op.create_index(op.f('ix_observations_encounter_id'), 'observations', ['encounter_id'], unique=False)
    op.create_index('ix_observations_patient_observed_at', 'observations', ['patient_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_observations_status'), 'observations', ['status'], unique=False)
    op.drop_index(op.f('ix_encounters_external_id'), table_name='encounters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_encounters_external_id'), 'encounters', ['external_id'], unique=False)
    op.drop_index(op.f('ix_observations_status'), table_name='observations')
    op.drop_index('ix_observations_patient_observed_at', table_name='observations')
    op.drop_index(op.f('ix_observations_encounter_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_code'), table_name='observations')
    op.drop_index(op.f('ix_observations_category'), table_name='observations')
    op.drop_table('observations')
    # ### end Alembic commands ###
