"""add conditions table

Revision ID: 685666386ae6
Revises: 2e57a73ca760
Create Date: 2026-07-28 15:17:02.101381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685666386ae6'
down_revision: Union[str, Sequence[str], None] = '2e57a73ca760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('code_system', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('clinical_status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('onset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abatement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_conditions_source_external_id')
    )
    op.create_index(op.f('ix_conditions_clinical_status'), 'conditions', ['clinical_status'], unique=False)
    op.create_index(op.f('ix_conditions_code'), 'conditions', ['code'], unique=False)
    op.create_index(op.f('ix_conditions_encounter_id'), 'conditions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_conditions_external_id'), 'conditions', ['external_id'], unique=False)
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_index(op.f('ix_conditions_onset_at'), 'conditions', ['onset_at'], unique=False)
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conditions_source_system'), 'conditions', ['source_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conditions_source_system'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_onset_at'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_external_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_encounter_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_code'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_clinical_status'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
