"""add diagnostic reports table

Revision ID: f3c250badef9
Revises: dd10de0050e3
Create Date: 2026-07-06 19:46:24.878594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c250badef9'
down_revision: Union[str, Sequence[str], None] = 'dd10de0050e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_name', 'object_key', name='uq_diagnostic_reports_bucket_object'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_diagnostic_reports_source_external_id')
    )
    op.create_index(op.f('ix_diagnostic_reports_encounter_id'), 'diagnostic_reports', ['encounter_id'], unique=False)
    op.create_index('ix_diagnostic_reports_patient_issued_at', 'diagnostic_reports', ['patient_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_diagnostic_reports_uploaded_by_id'), 'diagnostic_reports', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_reports_uploaded_by_id'), table_name='diagnostic_reports')
    op.drop_index('ix_diagnostic_reports_patient_issued_at', table_name='diagnostic_reports')
    op.drop_index(op.f('ix_diagnostic_reports_encounter_id'), table_name='diagnostic_reports')
    op.drop_table('diagnostic_reports')
    # ### end Alembic commands ###
